### ISSUE TITLE
doas model faddeva plugin incompatible with 0.0.15 API

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#275]
* glotaran version: 0.0.15 (just upgraded from 0.0.10)
* Python version: 3.7.5
* Operating System: Fedora 30

### Description

glotaran --version 
doas-fadeva plugin was loaded, but failed

### What I Did

```
$ glotaran --version
Traceback (most recent call last):
  File "/usr/local/bin/glotaran", line 11, in <module>
    load_entry_point('glotaran', 'console_scripts', 'glotaran')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "glotaran/glotaran/__init__.py", line 22, in <module>
    entry_point.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "glotaran-doas-faddeva/doasmodelfaddeva/__init__.py", line 1, in <module>
    from . import model
  File "glotaran-doas-faddeva/doasmodelfaddeva/model.py", line 5, in <module>
    from glotaran.builtin.models.kinetic_spectrum.kinetic_spectrum_model import (
ImportError: cannot import name 'spectral_constraint_penalty' from 'glotaran.builtin.models.kinetic_spectrum.kinetic_spectrum_model' (glotaran/glotaran/builtin/models/kinetic_spectrum/kinetic_spectrum_model.py)

```

**Comment by joernweissenborn** [comment]
Thisis not a glotaran issue. Plugins need catch up themselves or set
version constraints.

Am Di., 3. Dez. 2019 um 09:46 Uhr schrieb Joris Snellenburg <
notifications@github.com>:

**Comment by jsnel** [comment]
You are technically correct, so I will close this issue.

Only the built-in plugins are maintained as part of pyglotaran, extension will have to declare version constraints. Of course once the pyglotaran API is finalized this is expected to be be less of an issue.
