### ISSUE TITLE
Problem in optimization call with multiple dataset

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#462]
* glotaran version: 0.2.0 (9d8ef3e38d0d18b32a4f0fe0ced3b2b136c9a22f)
* Python version: 3.8.6
Note on branch feature/Issue460_Fix_for_crash_in_penalty_function in PR #461 

### NOTE
This issues should be obsolete after merging of PR #442 

### Description

Trying to call model.optimize with more than 1 dataset
```
model.optimize(parameter, {"dataset1": dataset1, "dataset2": dataset2}
```

### What I Did
Run [this example](https://github.com/glotaran/pyglotaran_examples/tree/problem_class_examples/case_studies/2007-Hippius_et_al-JPCC2007_Figs5_9/two_dataset_analysis.py 
) from [pyglotaran_examples](https://github.com/glotaran/pyglotaran_examples) 

```
Traceback (most recent call last):
  File "pyglotaran_examples/case_studies/2007-Hippius_et_al-JPCC2007_Figs5_9/two_dataset_analysis.py", line 53, in <module>
    result = model.optimize(parameter, {"dataset1": dataset1, "dataset2": dataset2}, verbose=True, max_nfev=10)
  File "pyglotaran\glotaran\model\base_model.py", line 207, in optimize
    return optimize(scheme, verbose=verbose, client=client)
  File "pyglotaran\glotaran\analysis\optimize.py", line 29, in optimize
    return optimize_task(initial_parameter, scheme, verbose)
  File "pyglotaran\glotaran\analysis\optimize.py", line 53, in optimize_task
    lm_result = minimizer.minimize(method="least_squares", verbose=verbose, max_nfev=scheme.nfev)
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\lmfit\minimizer.py", line 2285, in minimize
    return function(**kwargs)
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\lmfit\minimizer.py", line 1527, in least_squares
    ret = least_squares(self.__residual, start_vals,
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 807, in least_squares
    f0 = fun_wrapped(x0)
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 802, in fun_wrapped
    return np.atleast_1d(fun(x, *args, **kwargs))
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\lmfit\minimizer.py", line 590, in __residual
    return _nan_policy(np.asarray(out).ravel(),
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\lmfit\minimizer.py", line 2343, in _nan_policy
    mask = ~handler_func(arr)
  File ".conda\envs\gta_py38_con_dev\lib\site-packages\lmfit\minimizer.py", line 2337, in <lambda>
    handler_func = lambda x: ~np.isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by jsnel** [comment]
This issue was resolved as part of the major refactor leading up the the v0.3.0 release.
