### ISSUE TITLE
In two dataset (grouped) analysis self._full_clp_labels is None

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#478]
* glotaran version: v0.2.0 (312e075026f26ef4490c747a958d27ff6cb7e4b7 from PR477)
* Python version: 3.8.5
* Operating System: Windows 10

### Description

First patch with PR477 since otherwise another crash is observed prior to reaching the point of the traceback below.
When running a [(two) dataset analysis](https://github.com/glotaran/pyglotaran_examples/blob/master/examples/two_dataset/two_dataset_analysis.py) with [equal_area_penalties in the model](https://github.com/glotaran/pyglotaran_examples/blob/master/examples/two_dataset/models/equareasim2_model.yaml) a crash is observed due clp_labels being None
Two dataset so grouped, call to self.calculate_index_dependent_grouped_residual()
In the call of _calculate_additional_grouped_penalty  self._full_clp_labels is None
### What I Did

```
Traceback (most recent call last):
  File "c:/src/pyglotaran_examples/examples/two_dataset/two_dataset_analysis.py", line 60, in <module>
    result = optimize(scheme)
  File "c:\src\pyglotaran\glotaran\analysis\optimize.py", line 27, in optimize
    lm_result = minimizer.minimize(method="least_squares", verbose=verbose, max_nfev=scheme.nfev)
  File ".envs\py38gta_pdev\lib\site-packages\lmfit\minimizer.py", line 2285, in minimize
    return function(**kwargs)
  File ".envs\py38gta_pdev\lib\site-packages\lmfit\minimizer.py", line 1527, in least_squares
    ret = least_squares(self.__residual, start_vals,
  File ".envs\py38gta_pdev\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 807, in least_squares
    f0 = fun_wrapped(x0)
  File ".envs\py38gta_pdev\lib\site-packages\scipy\optimize\_lsq\least_squares.py", line 802, in fun_wrapped
    return np.atleast_1d(fun(x, *args, **kwargs))
  File ".envs\py38gta_pdev\lib\site-packages\lmfit\minimizer.py", line 576, in __residual
    out = self.userfcn(params, *self.userargs, **self.userkws)
  File "c:\src\pyglotaran\glotaran\analysis\optimize.py", line 48, in _calculate_penalty
    return problem.full_penalty
  File "c:\src\pyglotaran\glotaran\analysis\problem.py", line 239, in full_penalty
    residuals = self.weighted_residuals
  File "c:\src\pyglotaran\glotaran\analysis\problem.py", line 217, in weighted_residuals
    self.calculate_residual()
  File "c:\src\pyglotaran\glotaran\analysis\problem.py", line 540, in calculate_residual
    self.calculate_index_dependent_grouped_residual()
  File "c:\src\pyglotaran\glotaran\analysis\problem.py", line 615, in calculate_index_dependent_grouped_residual
    self._calculate_additional_grouped_penalty()
  File "c:\src\pyglotaran\glotaran\analysis\problem.py", line 809, in _calculate_additional_grouped_penalty
    self._additional_penalty = self.model.additional_penalty_function(
  File "c:\src\pyglotaran\glotaran\builtin\models\kinetic_spectrum\spectral_penalties.py", line 87, in apply_spectral_penalties
    index_clp_label = clp_labels[i] if model.index_dependent() else clp_labels
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jsnel** [comment]
@joernweissenborn  please refer to this test case:
https://github.com/glotaran/pyglotaran_examples/blob/master/examples/two_dataset/two_dataset_analysis.py

**Comment by joernweissenborn** [comment]
There should be nothing like _full_clp_labels, they just be the
self._clp_labels. There is no full there. It might be confusing because you
have _full_clp. those should be nemade just clp.

Am So., 6. Dez. 2020 um 15:34 Uhr schrieb Joris Snellenburg <
notifications@github.com>:

**Comment by jsnel** [comment]
Related to #472
